### ISSUE TITLE
Create a user story for the user 'Aggregator'

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dataservices-architecture#3]
User scenarios described [here](https://docs.google.com/document/d/1RHv4GegqUk9NxToasc4xmKbKqWgu0NCGBMs0eBb2lhc/edit?usp=sharing)
- [x] NDE Dataset Register user
- [x] Clariah harvester
- [x] Netwerk Oorlogsbronnen user
- [x] (Future) European LOD aggregator user (LODA) (zie oudere architectuurplaat)
- [x] (Current) European/EUscreen aggregator user (will not model this)

**Comment by wmelder** [comment]
Willem vraagt dimitra

**Comment by wmelder** [comment]
Dimitra gaat reviewen.

**Comment by wmelder** [comment]
updaten met opmerkingen Dimitra
